version: '3.8'
services:
  app:
    build: .
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/Sirma
      SPRING_DATASOURCE_USERNAME: pavelpetrov
      SPRING_DATASOURCE_PASSWORD: 20010407p
      SPRING_JPA_HIBERNATE_DDL_AUTO: create-drop

  db:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: Sirma
      POSTGRES_USER: pavelpetrov
      POSTGRES_PASSWORD: 20010407p
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
